### ISSUE TITLE
(current-line)

### ISSUE THREAD

**Issue by Whil-** [Kinneyzhang/gk-roam.el#29]
Hi,

testing this package out. Getting some errors in the process. One of those is the use of a function called `current-line`, which is not declared and does not exist in stock emacs (at least in the version I'm on, 27.1).

**Comment by Whil-** [comment]
I'm guessing you meant to use `line-number-at-pos`?

**Comment by Kinneyzhang** [comment]
Thanks, ```line-number-at-pos``` should be a better alternative to ```current-line```.

 Actually, I got the same error in linux but not in Mac, so I add ```(require 'array)``` in code (current-line function is defined in array.el which is a built in Elisp file in Mac). But consider of difference OS, ```line-number-at-pos``` is more common since it's defined in simple.el. 

I will replace it. Thanks again!
